exp:
    exp_dir: experiments/gan/base_gan_test
    device: cuda
    seed: 777
    use_wandb: True
    model_type: gan

wandb:
    WANDB_KEY: null
    run_id: null
    entity: artem-fm
    project: gan
    run_name: base_gan_test
    tags: ["gan", "base"]

data:
    dataset_name: base_dataset
    input_train_dir: data/food_data/train
    input_val_dir: data/food_data/test
    normalize_data: True
    samples_to_normalize: null
    norm_mean: [0.5, 0.5, 0.5]
    norm_std: [0.5, 0.5, 0.5]
    train_batch_size: 64
    val_batch_size: 8
    n_save_images: 8
    workers: 8

train:
    checkpoint_path: null
    models:
        trainer: base_gan_trainer
        generator: base_gen
        discriminator: base_disc
        gen_optimizer: adam
        disc_optimizer: adam

    proccessing:
        start_step: 0
        steps: 2000000
        log_step: 200
        checkpoint_step: 15000
        val_step: 15000
    
    use_amp: True
    val_metrics: ["fid/isc/kid"]

generator_args:
    z_dim: 32
    hidden_dim: 512
    blocks_num: 4

discriminator_args:
    hidden_dim: 512
    blocks_num: 4

gen_optimizer_args:
    lr: 0.0001

disc_optimizer_args:
    lr: 0.0001

gen_losses:
    softplus_gen: 1.0

disc_losses:
    softplus_disc: 1.0

loss_args: []