exp:
    exp_dir: experiments/wasserstain_gan
    device: mps
    seed: 777
    use_wandb: True
    model_type: gan

wandb:
    WANDB_KEY: null
    run_id: null
    entity: artem-fm
    project: gan
    run_name: base_gan_test
    tags: ["gan", "base"]

data:
    dataset_name: base_dataset
    input_train_dir: data/food_data/train
    input_val_dir: data/food_data/test
    normalize_data: True
    samples_to_normalize: null
    train_batch_size: 8
    val_batch_size: 8
    workers: 8

train:
    checkpoint_path: null
    trainer: wasserstain_gan_trainer
    generator: wasserstain_gen
    critic: wasserstain_critic
    gen_optimizer: adam
    critic_optimizer: rmsprop
    add_noise: False
    use_amp: False
    val_metrics: ["fid/isc/kid"]
    start_step: 0
    steps: 300000
    log_step: 500
    checkpoint_step: 15000
    val_step: 15000

generator_args:
    z_dim: 128
    hidden_dim: 512

critic_args:
    hidden_dim: 512

gen_optimizer_args:
    lr: 0.001

critic_optimizer_args:
    lr: 0.0001
    momentum: 0.1

gen_losses:
    wasserstain_gen: 1.0

disc_losses:
    wasserstain_critic: 1.0
    wasserstein_gp: 10.0

loss_args: []