exp:
    exp_dir: experiments/base_gan_test
    device: mps
    seed: 777
    use_wandb: True
    model_type: gan

wandb:
    WANDB_KEY: null
    run_id: null
    entity: artem-fm
    project: gan
    run_name: base_gan_test
    tags: ["gan", "base"]

data:
    dataset_name: base_dataset
    input_train_dir: data/food_data/train
    input_val_dir: data/food_data/test
    normalize_data: False
    samples_to_normalize: null
    train_batch_size: 8
    val_batch_size: 8
    workers: 8

train:
    checkpoint_path: null
    trainer: base_gan_trainer
    generator: base_gen
    discriminator: base_disc
    gen_optimizer: adam
    disc_optimizer: adam
    use_amp: False
    val_metrics: ["fid/isc/kid"]
    start_step: 0
    steps: 300000
    log_step: 500
    checkpoint_step: 15000
    val_step: 15000

generator_args:
    z_dim: 32
    hidden_dim: 512
    blocks_num: 4

discriminator_args:
    hidden_dim: 512
    blocks_num: 4

gen_optimizer_args:
    lr: 0.0001

disc_optimizer_args:
    lr: 0.0001

losses:
    - gen_losses
    - disc_losses

gen_losses:
    softplus_gen: 1.0

disc_losses:
    softplus_disc: 1.0

loss_args: []